### ISSUE TITLE
Can't download videos

### ISSUE THREAD

**Issue by felipe-bustamante** [sunaram/dirtyship-downloader#1]
Hello, I tried your app (in mac) but a have an error:

./dirtyship-downloader-macos https://dirtyship.com/amouranth-lewd-cowgirl-leaked-patreon-video/       ✔  753  17:14:40
Downloading https://cdn2.dirtyship.net/cdn2/AmouranthCowgirlv.mp4 to outputs/amouranth-lewd-cowgirl-leaked-patreon-video/AmouranthCowgirlv.mp4
Error: Failed to get 'https://cdn2.dirtyship.net/cdn2/AmouranthCowgirlv.mp4' (403)
    at ClientRequest.<anonymous> (/snapshot/dirtyship-downloader/lib/utility.js:17:16)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)

Did I something wrong? 
Thank you!

**Comment by sunaram** [comment]
I will try to push a fix soon. I think it's because they are using cloudfare now.

**Comment by felipe-bustamante** [comment]
Thank you!!!

**Comment by sunaram** [comment]
Fixed.
Please download the latest version (v1.0.1) from "releases"

**Comment by felipe-bustamante** [comment]
Hello, thank you for your support!
I tried again, but inside the output folder there is another folder (amouranth) empty.... no videos inside...
I have to do something special?
thank you again!
Felipe.

**Comment by felipe-bustamante** [comment]
Thank you!!!!!!!!!
Now works perfectly!!
BR
Felipe
